# Generated by Django 5.2.7 on 2025-10-03 09:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], help_text='Month number (1, 2, 3, etc.)')),
                ('year', models.IntegerField()),
                ('company_profile', models.TextField(blank=True, help_text='Profil perusahaan (bulan pertama saja)')),
                ('job_description', models.TextField(help_text='Job description dan tugas yang dikerjakan', validators=[django.core.validators.MinLengthValidator(500, 'Minimal 500 karakter')])),
                ('work_environment', models.TextField(help_text='Suasana lingkungan kerja', validators=[django.core.validators.MinLengthValidator(100, 'Minimal 100 karakter')])),
                ('useful_skills', models.TextField(help_text='Skills dari kuliah yang berguna', validators=[django.core.validators.MinLengthValidator(100, 'Minimal 100 karakter')])),
                ('needed_skills', models.TextField(help_text='Skills yang dibutuhkan tapi belum dipelajari', validators=[django.core.validators.MinLengthValidator(100, 'Minimal 100 karakter')])),
                ('achievements', models.TextField(help_text='Achievement bulan ini', validators=[django.core.validators.MinLengthValidator(100, 'Minimal 100 karakter')])),
                ('challenges', models.TextField(help_text='Kendala yang dihadapi', validators=[django.core.validators.MinLengthValidator(100, 'Minimal 100 karakter')])),
                ('next_month_plan', models.TextField(help_text='Rencana bulan depan', validators=[django.core.validators.MinLengthValidator(100, 'Minimal 100 karakter')])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('REVISION_REQUESTED', 'Revision Requested')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='internships.internshipplacement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-year', '-month'],
                'unique_together': {('placement', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ReportFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('requires_revision', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='reports.monthlyreport')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Feedback',
                'verbose_name_plural': 'Report Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
